### ISSUE TITLE
No Package libselinux-python available when running configure_ovirt_machines_for_metrics.sh

### ISSUE THREAD

**Issue by okamidash** [oVirt/ovirt-engine-metrics#2]
Ovirt version: 4.4.1
OS: Centos 8

The role ovirt.linux-system-roles-logging has the wrong variable set to install rsyslog.

The var is `rsyslog_base_packages`.
File path: `/usr/share/ansible/roles/oVirt.metrics/roles/oVirt.linux-system-roles-logging/roles/rsyslog/defaults/main.yaml configure_ovirt_machines_for_metrics.sh`

It attempts to install `libselinux-python` but the correct package is `python3-libselinux`.
Changing the value to the correct one seems to do the trick, as the script runs successfully.

**Comment by avlitman** [comment]
> @avlitman, could it be possible for you to check the logging role version used in ovirt? Thanks.

We require rhel-system-roles >= 1.7.2-1

**Comment by nhosoi** [comment]
Thank you, @avlitman!

If rhel-system-roles >= 1.7.2-1 is being used with ovirt, the logging role in it is newer or equal to version [1.4.0](https://github.com/linux-system-roles/logging/releases/tag/1.4.0), which includes the commit in https://github.com/oVirt/ovirt-engine-metrics/issues/2#issuecomment-954011503.
